### ISSUE TITLE
Expose a Rest API

### ISSUE THREAD

**Issue by rafaeljesus** [aalvesjr/calcula_ir#3]
Maybe we could espose a rest api for calculating the taxes wdyt @aalvesjr? 

Just for fun 😉

**Comment by aalvesjr** [comment]
could be @rafaeljesus \o/, I'll create a new project, and use this models from here.

**Comment by aalvesjr** [comment]
Jisas @rafaeljesus , the model "Salario" was moved to another repository, and created one new [calcula_ir_api](https://github.com/aalvesjr/calcula_ir_api) to expose this model between an api.

**Comment by aalvesjr** [comment]
Jisas @rafaeljesus , the model "Salario" was moved to another repository, and created one new [calcula_ir_api](https://github.com/aalvesjr/calcula_ir_api) to expose this model between an api.
